http:
  port: 8080
admin:
  port: 9876
  hostname: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
apiEndpoints:
  auth:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/*'
  authAdmin:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/*'
  users:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/*'
  admin:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/*'
  products:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/*'
  banners:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/*'
  general:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/*'
  report:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/*'
  search:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/*'
  orders:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/*'
serviceEndpoints:
  authService:
    url: 'http://localhost:9001'
  authAdminService:
    url: 'http://localhost:9002'
  usersService:
    url: 'http://localhost:9003'
  adminService:
    url: 'http://localhost:9004'
  productsService:
    url: 'http://localhost:9005'
  bannersService:
    url: 'http://localhost:9006'
  generalService:
    url: 'http://localhost:9007'
  reportService:
    url: 'http://localhost:9008'
  searchService:
    url: 'http://localhost:9009'
  ordersService:
    url: 'http://localhost:9010'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: auth-service
    apiEndpoints:
      - auth
    policies:
      - proxy:
          - action:
              serviceEndpoint: authService
              changeOrigin: true

  - name: auth-admin-service
    apiEndpoints:
      - authAdmin
    policies:
      - proxy:
          - action:
              serviceEndpoint: authAdminService
              changeOrigin: true

  - name: users-service
    apiEndpoints:
      - users
    policies:
      - proxy:
          - action:
              serviceEndpoint: usersService
              changeOrigin: true

  - name: admin-service
    apiEndpoints:
      - admin
    policies:
      - proxy:
          - action:
              serviceEndpoint: adminService
              changeOrigin: true

  - name: products-service
    apiEndpoints:
      - products
    policies:
      - proxy:
          - action:
              serviceEndpoint: productsService
              changeOrigin: true

  - name: banners-service
    apiEndpoints:
      - banners
    policies:
      - proxy:
          - action:
              serviceEndpoint: bannersService
              changeOrigin: true

  - name: general-service
    apiEndpoints:
      - general
    policies:
      - proxy:
          - action:
              serviceEndpoint: generalService
              changeOrigin: true

  - name: report-service
    apiEndpoints:
      - report
    policies:
      - proxy:
          - action:
              serviceEndpoint: reportService
              changeOrigin: true

  - name: search-service
    apiEndpoints:
      - search
    policies:
      - proxy:
          - action:
              serviceEndpoint: searchService
              changeOrigin: true
  - name: orders-service
    apiEndpoints:
      - orders
    policies:
      - proxy:
          - action:
              serviceEndpoint: ordersService
              changeOrigin: true
