http:
  port: 8080
admin:
  port: 9876
  hostname: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
apiEndpoints:
  auth:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/auth/user'
      - '/api/v1/request/user/forgot-password'
      - '/api/v1/confirm/user/forgot-password'
  authAdmin:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/auth/admin'
  users:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/users'
      - '/api/v1/user/*'
      - '/api/v1/user-addresses/*'
      - '/api/v1/user-address'
      - '/api/v1/user-address/*'
      - '/api/v1/user-banks/*'
      - '/api/v1/user-bank'
      - '/api/v1/user-bank/*'
      - '/api/v1/user-creditcard'
      - '/api/v1/user-creditcard/*'
      - '/api/v1/user-reviews/*'
      - '/api/v1/user-review'
      - '/api/v1/user-review/*'
  admin:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/admin/*'
  products:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/products'
      - '/api/v1/products/*'
      - '/api/v1/product/*'
      - '/api/v1/product-brands'
      - '/api/v1/product-brands/*'
      - '/api/v1/product-categories'
      - '/api/v1/product-subcategories'
      - '/api/v1/product-subcategories/*'
      - '/api/v1/wishlist'
      - '/api/v1/wishlist/*'
      - '/api/v1/cart'
      - '/api/v1/cart/*'
  banners:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/banner'
      - '/api/v1/banner/*'
      - '/api/v1/banners'
      - '/api/v1/banners/*'
      - '/api/v1/product-banners'
      - '/api/v1/product-banners/*'
  general:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/general/*'
  report:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/report'
      - '/api/v1/report/*'
      - '/api/v1/reports'
  search:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/search'
  orders:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/order'
      - '/api/v1/order/*'
  promo:
    host: ec2-52-77-224-133.ap-southeast-1.compute.amazonaws.com
    paths:
      - '/api/v1/promo'
      - '/api/v1/promo/*'
serviceEndpoints:
  authService:
    url: 'http://localhost:9001'
  authAdminService:
    url: 'http://localhost:9002'
  usersService:
    url: 'http://localhost:9003'
  adminService:
    url: 'http://localhost:9004'
  productsService:
    url: 'http://localhost:9005'
  bannersService:
    url: 'http://localhost:9006'
  generalService:
    url: 'http://localhost:9007'
  reportService:
    url: 'http://localhost:9008'
  searchService:
    url: 'http://localhost:9009'
  ordersService:
    url: 'http://localhost:9010'
  promoService:
    url: 'http://localhost:9011'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: auth-service
    apiEndpoints:
      - auth
    policies:
      - proxy:
          - action:
              serviceEndpoint: authService
              changeOrigin: true

  - name: auth-admin-service
    apiEndpoints:
      - authAdmin
    policies:
      - proxy:
          - action:
              serviceEndpoint: authAdminService
              changeOrigin: true

  - name: users-service
    apiEndpoints:
      - users
    policies:
      - proxy:
          - action:
              serviceEndpoint: usersService
              changeOrigin: true

  - name: admin-service
    apiEndpoints:
      - admin
    policies:
      - proxy:
          - action:
              serviceEndpoint: adminService
              changeOrigin: true

  - name: products-service
    apiEndpoints:
      - products
    policies:
      - proxy:
          - action:
              serviceEndpoint: productsService
              changeOrigin: true

  - name: banners-service
    apiEndpoints:
      - banners
    policies:
      - proxy:
          - action:
              serviceEndpoint: bannersService
              changeOrigin: true

  - name: general-service
    apiEndpoints:
      - general
    policies:
      - proxy:
          - action:
              serviceEndpoint: generalService
              changeOrigin: true

  - name: report-service
    apiEndpoints:
      - report
    policies:
      - proxy:
          - action:
              serviceEndpoint: reportService
              changeOrigin: true

  - name: search-service
    apiEndpoints:
      - search
    policies:
      - proxy:
          - action:
              serviceEndpoint: searchService
              changeOrigin: true
  - name: orders-service
    apiEndpoints:
      - orders
    policies:
      - proxy:
          - action:
              serviceEndpoint: ordersService
              changeOrigin: true
  - name: promo-service
    apiEndpoints:
      - promo
    policies:
      - proxy:
          - action:
              serviceEndpoint: promoService
              changeOrigin: true
