
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('table_name').del()
    .then(function () {
      // Inserts seed entries
      return knex('table_name').insert([
        {city: 'Kabupaten Aceh Barat', province_id: 1},
        {city: 'Kabupaten Aceh Barat Daya', province_id: 1},
        {city: 'Kabupaten Aceh Besar', province_id: 1},
        {city: 'Kabupaten Aceh Jaya', province_id: 1},
        {city: 'Kabupaten Aceh Selatan', province_id: 1},
        {city: 'Kabupaten Aceh Singkil', province_id: 1},
        {city: 'Kabupaten Aceh Tamiang', province_id: 1},
        {city: 'Kabupaten Aceh Tengah', province_id: 1},
        {city: 'Kabupaten Aceh Tenggara', province_id: 1},
        {city: 'Kabupaten Aceh Timur', province_id: 1},
        {city: 'Kabupaten Aceh Utara', province_id: 1},
        {city: 'Kabupaten Bener Meriah', province_id: 1},
        {city: 'Kabupaten Bireuen', province_id: 1},
        {city: 'Kabupaten Gayo Lues', province_id: 1},
        {city: 'Kabupaten Nagan Raya', province_id: 1},
        {city: 'Kabupaten Pidie', province_id: 1},
        {city: 'Kabupaten Pidie Jaya', province_id: 1},
        {city: 'Kabupaten Simeulue', province_id: 1},
        {city: 'Kota Banda Aceh', province_id: 1},
        {city: 'Kota Langsa', province_id: 1},
        {city: 'Kota Lhoksumawe', province_id: 1},
        {city: 'Kota Sabang', province_id: 1},
        {city: 'Kota Sabulussalam', province_id: 1},
        {city: 'Kabupaten Badung', province_id: 2},
        {city: 'Kabupaten Bangil', province_id: 2},
        {city: 'Kabupaten Buleleng', province_id: 2},
        {city: 'Kabupaten Gianyar', province_id: 2},
        {city: 'Kabupaten Jembrana', province_id: 2},
        {city: 'Kabupaten Karangasem', province_id: 2},
        {city: 'Kabupaten Klungkung', province_id: 2},
        {city: 'Kabupaten Tabanan', province_id: 2},
        {city: 'Kota Denpasar', province_id: 2},
        {city: 'Kabupaten Lebak', province_id: 3},
        {city: 'Kabupaten Pandeglang', province_id: 3},
        {city: 'Kabupaten Serang', province_id: 3},
        {city: 'Kabupaten Tangerang', province_id: 3},
        {city: 'Kota Cilegon', province_id: 3},
        {city: 'Kota Serang', province_id: 3},
        {city: 'Kota Tangerang', province_id: 3},
        {city: 'Kota Tangerang Selatan', province_id: 3},
        {city: 'Kabupaten Bengkulu Selatan', province_id: 4},
        {city: 'Kabupaten Bengkulu Tengah', province_id: 4},
        {city: 'Kabupaten Bengkulu Utara', province_id: 4},
        {city: 'Kabupaten Kaur', province_id: 4},
        {city: 'Kabupaten Kepahiang', province_id: 4},
        {city: 'Kabupaten Lebong', province_id: 4},
        {city: 'Kabupaten Mukomuko', province_id: 4},
        {city: 'Kabupaten Rejang Lebonh', province_id: 4},
        {city: 'Kabupaten Seluma', province_id: 4},
        {city: 'Kota Bengkulu', province_id: 4},
        {city: 'Kabupaten Boalemo', province_id: 5},
        {city: 'Kabupaten Bone Bolango', province_id: 5},
        {city: 'Kabupaten Gorontalo', province_id: 5},
        {city: 'Kabupaten Gorontalo Utara', province_id: 5},
        {city: 'Kabupaten Pohuato', province_id: 5},
        {city: 'Kota Gorontalo', province_id: 5},
        {city: 'Jakarta Barat', province_id: 6},
        {city: 'Jakarta Pusat', province_id: 6},
        {city: 'Jakarta Selatan', province_id: 6},
        {city: 'Jakarta Timur', province_id: 6},
        {city: 'Jakarta Utara', province_id: 6},
        {city: 'Kepulauan Seribu', province_id: 6},
        {city: 'Kabupaten Batanghari', province_id: 7},
        {city: 'Kabupaten Bungo', province_id: 7},
        {city: 'Kabupaten Kerinci', province_id: 7},
        {city: 'Kabupaten Merangin', province_id: 7},
        {city: 'Kabupaten Muaro Jambi', province_id: 7},
        {city: 'Kabupaten Sarolangun', province_id: 7},
        {city: 'Kabupaten Tanjung Jabung Barat', province_id: 7},
        {city: 'Kabupaten Tanjung Jabung Timur', province_id: 7},
        {city: 'Kabupaten Tebo', province_id: 7},
        {city: 'Kota Jambi', province_id: 7},
        {city: 'Kota Sungaipenuh', province_id: 7},
        {city: 'Kabupaten Bandung', province_id: 8},
        {city: 'Kabupaten Bandung Barat', province_id: 8},
        {city: 'Kabupaten Bekasi', province_id: 8},
        {city: 'Kabupaten Bogor', province_id: 8},
        {city: 'Kabupaten Ciamis', province_id: 8},
        {city: 'Kabupaten Cianjur', province_id: 8},
        {city: 'Kabupaten Cirebon', province_id: 8},
        {city: 'Kabupaten Garut', province_id: 8},
        {city: 'Kabupaten Indramayu', province_id: 8},
        {city: 'Kabupaten Karawang', province_id: 8},
        {city: 'Kabupaten Kuningan', province_id: 8},
        {city: 'Kabupaten Majalengka', province_id: 8},
        {city: 'Kabupaten Pangandaran', province_id: 8},
        {city: 'Kabupaten Purwakarta', province_id: 8},
        {city: 'Kabupaten Subang', province_id: 8},
        {city: 'Kabupaten Sukabumi', province_id: 8},
        {city: 'Kabupaten Sumedang', province_id: 8},
        {city: 'Kabupaten Tasikmalaya', province_id: 8},
        {city: 'Kota Bandung', province_id: 8},
        {city: 'Kota Banjar', province_id: 8},
        {city: 'Kota Bekasi', province_id: 8},
        {city: 'Kota Bogor', province_id: 8},
        {city: 'Kota Cimahi', province_id: 8},
        {city: 'Kota Cirebon', province_id: 8},
        {city: 'Kota Depok', province_id: 8},
        {city: 'Kota Sukabumi', province_id: 8},
        {city: 'Kota Tasikmalaya', province_id: 8},
        {city: 'Kabupaten Banjarnegara', province_id: 9},
        {city: 'Kabupaten Banyumas', province_id: 9},
        {city: 'Kabupaten Batang', province_id: 9},
        {city: 'Kabupaten Biora', province_id: 9},
        {city: 'Kabupaten Boyolali', province_id: 9},
        {city: 'Kabupaten Brebes', province_id: 9},
        {city: 'Kabupaten Cilacap', province_id: 9},
        {city: 'Kabupaten Demak', province_id: 9},
        {city: 'Kabupaten Grobogan', province_id: 9},
        {city: 'Kabupaten Jepara', province_id: 9},
        {city: 'Kabupaten Karanganyar', province_id: 9},
        {city: 'Kabupaten Kebumen', province_id: 9},
        {city: 'Kabupaten Kendal', province_id: 9},
        {city: 'Kabupaten Klaten', province_id: 9},
        {city: 'Kabupaten Kudus', province_id: 9},
        {city: 'Kabupaten Magelang', province_id: 9},
        {city: 'Kabupaten Pati', province_id: 9},
        {city: 'Kabupaten Pekalongan', province_id: 9},
        {city: 'Kabupaten Pemalang', province_id: 9},
        {city: 'Kabupaten Purbalingga', province_id: 9},
        {city: 'Kabupaten Purworejo', province_id: 9},
        {city: 'Kabupaten Rembang', province_id: 9},
        {city: 'Kabupaten Semarang', province_id: 9},
        {city: 'Kabupaten Sragen', province_id: 9},
        {city: 'Kabupaten Sukoharjo', province_id: 9},
        {city: 'Kabupaten Tegal', province_id: 9},
        {city: 'Kabupaten Temanggung', province_id: 9},
        {city: 'Kabupaten Wonogiri', province_id: 9},
        {city: 'Kabupaten Wonosobo', province_id: 9},
        {city: 'Kota Magelang', province_id: 9},
        {city: 'Kota Pekalongan', province_id: 9},
        {city: 'Kota Salatiga', province_id: 9},
        {city: 'Kota Semarang', province_id: 9},
        {city: 'Kota Surakarta', province_id: 9},
        {city: 'Kota Tegal', province_id: 9},
        {city: 'Kabupaten Bangkalan', province_id: 10,
        {city: 'Kabupaten Banyuwangi', province_id: 10},
        {city: 'Kabupaten Blitar', province_id: 10},
        {city: 'Kabupaten Bojonegoro', province_id: 10},
        {city: 'Kabupaten Bondowoso', province_id: 10,
        {city: 'Kabupaten Gresik', province_id: 10},
        {city: 'Kabupaten Jember', province_id: 10},
        {city: 'Kabupaten Jombang', province_id: 10},
        {city: 'Kabupaten Kediri', province_id: 10,
        {city: 'Kabupaten Lamongan', province_id: 10},
        {city: 'Kabupaten Lumajang', province_id: 10},
        {city: 'Kabupaten Madiun', province_id: 10},
        {city: 'Kabupaten Magetan', province_id: 10,
        {city: 'Kabupaten Malang', province_id: 10},
        {city: 'Kabupaten Mojokerto', province_id: 10},
        {city: 'Kabupaten Nganjuk', province_id: 10},
        {city: 'Kabupaten Ngawi', province_id: 10,
        {city: 'Kabupaten Pacitan', province_id: 10},
        {city: 'Kabupaten Pamekasan', province_id: 10},
        {city: 'Kabupaten Pasuruan', province_id: 10},
        {city: 'Kabupaten Ponorogo', province_id: 10,
        {city: 'Kabupaten Probolinggo', province_id: 10},
        {city: 'Kabupaten Sampang', province_id: 10},
        {city: 'Kabupaten Sidoarjo', province_id: 10},
        {city: 'Kabupaten Situbondo', province_id: 10,
        {city: 'Kabupaten Sumenep', province_id: 10},
        {city: 'Kabupaten Trenggalek', province_id: 10},
        {city: 'Kabupaten Tuban', province_id: 10},
        {city: 'Kabupaten Tulungagung', province_id: 10,
        {city: 'Kota Batu', province_id: 10},
        {city: 'Kota Blitar', province_id: 10},
        {city: 'Kota Kediri', province_id: 10},
        {city: 'Kota Madiun', province_id: 10,
        {city: 'Kota Mojokerto', province_id: 10},
        {city: 'Kota Pasuruan', province_id: 10},
        {city: 'Kota Probolinggo', province_id: 10},
        {city: 'Kota Surabaya', province_id: 10},
        {city: 'Kabupaten Bengkayang', province_id: 11},
        {city: 'Kabupaten Kapuas Hulu', province_id: 11},
        {city: 'Kabupaten Kayong Utara', province_id: 11},
        {city: 'Kabupaten Ketapang', province_id: 11},
        {city: 'Kabupaten Kubu Raya', province_id: 11},
        {city: 'Kabupaten Landak', province_id: 11},
        {city: 'Kabupaten Melawi', province_id: 11},
        {city: 'Kabupaten Mempawah', province_id: 11},
        {city: 'Kabupaten Sambas', province_id: 11},
        {city: 'Kabupaten Sanggau', province_id: 11},
        {city: 'Kabupaten Sekadau', province_id: 11},
        {city: 'Kabupaten Sintang', province_id: 11},
        {city: 'Kota Pontianak', province_id: 11},
        {city: 'Kota Singkawang', province_id: 11},
        {city: 'Kabupaten Balangan', province_id: 12},
        {city: 'Kabupaten Banjar', province_id: 12},
        {city: 'Kabupaten Barito Kuala', province_id: 12},
        {city: 'Kabupaten Hulu Sungai Selatan', province_id: 12},
        {city: 'Kabupaten Hulu Sungai Tengah', province_id: 12},
        {city: 'Kabupaten Hulu Sungai Utara', province_id: 12},
        {city: 'Kabupaten Kotabaru', province_id: 12},
        {city: 'Kabupaten Tabalong', province_id: 12},
        {city: 'Kabupaten Tanah Bumbu', province_id: 12},
        {city: 'Kabupaten Tanah Laut', province_id: 12},
        {city: 'Kabupaten Tapin', province_id: 12},
        {city: 'Kota Banjarbaru', province_id: 12},
        {city: 'Kota Banjarmasin', province_id: 12},
        {city: 'Kabupaten Barito Selatan', province_id: 13},
        {city: 'Kabupaten Barito Timur', province_id: 13},
        {city: 'Kabupaten Barito Utara', province_id: 13},
        {city: 'Kabupaten Gunungmas', province_id: 13},
        {city: 'Kabupaten Kapuas', province_id: 13},
        {city: 'Kabupaten Katingan', province_id: 13},
        {city: 'Kabupaten Kotawaringin Barat', province_id: 13},
        {city: 'Kabupaten Kotawaringin Timur', province_id: 13},
        {city: 'Kabupaten Lamandau', province_id: 13},
        {city: 'Kabupaten Murung Raya', province_id: 13},
        {city: 'Kabupaten Pulang Pisau', province_id: 13},
        {city: 'Kabupaten Sukamara', province_id: 13},
        {city: 'Kabupaten Seruyan', province_id: 13},
        {city: 'Kota Palangka Raya', province_id: 13},
        {city: 'Kabupaten Nunukan', province_id: 14},
        {city: 'Kabupaten Malinau', province_id: 14},
        {city: 'Kabupaten Bulungan', province_id: 14},
        {city: 'Kabupaten Tana Tidung', province_id: 14},
        {city: 'Kota Tarakan', province_id: 14},
        {city: 'Kabupaten Bangka', province_id: 15},
        {city: 'Kabupaten Belitung', province_id: 15},
        {city: 'Kabupaten Bangka Barat', province_id: 15},
        {city: 'Kabupaten Bangka Tengah', province_id: 15},
        {city: 'Kabupaten Bangka Selatan', province_id: 15},
        {city: 'Kabupaten Belitung Timur', province_id: 15},
        {city: 'Kota Pangkalpinang', province_id: 15},
        {city: 'Kabupaten Bintan Kepulauan', province_id: 16},
        {city: 'Kabupaten Karimun', province_id: 16},
        {city: 'Kabupaten Kepulauan Anambas', province_id: 16},
        {city: 'Kabupaten Lingga', province_id: 16},
        {city: 'Kabupaten Natuna', province_id: 16},
        {city: 'Kota Batam', province_id: 16},
        {city: 'Kota Tanjung Pinang', province_id: 16},
        {city: 'Kabupaten Lampung Barat', province_id: 17},
        {city: 'Kabupaten Lampung Selatan', province_id: 17},
        {city: 'Kabupaten Lampung Tengah', province_id: 17},
        {city: 'Kabupaten Lampung Timur', province_id: 17},
        {city: 'Kabupaten Lampung Utara', province_id: 17},
        {city: 'Kabupaten Mesuji', province_id: 17},
        {city: 'Kabupaten Pesawaran', province_id: 17},
        {city: 'Kabupaten Pesisir Barat', province_id: 17},
        {city: 'Kabupaten Pringsewu', province_id: 17},
        {city: 'Kabupaten Tanggamus', province_id: 17},
        {city: 'Kabupaten Tulang Bawang', province_id: 17},
        {city: 'Kabupaten Tulang Bawang Barat', province_id: 17},
        {city: 'Kabupaten Tulang Way Kanan', province_id: 17},
        {city: 'Kota Bandar Lampung', province_id: 17},
        {city: 'Kota Metro', province_id: 17},
        {city: 'Kabupaten Buru', province_id: 18},
        {city: 'Kabupaten Buru Selatan', province_id: 18},
        {city: 'Kabupaten Kepulauan Aru', province_id: 18},
        {city: 'Kabupaten Maluku Barat Daya', province_id: 18},
        {city: 'Kabupaten Maluku Tengah', province_id: 18},
        {city: 'Kabupaten Maluku Tenggara Barat', province_id: 18},
        {city: 'Kabupaten Seram Bagian Barat', province_id: 18},
        {city: 'Kabupaten Seram Bagian Timur', province_id: 18},
        {city: 'Kota Ambon', province_id: 18},
        {city: 'Kota Tual', province_id: 18},
        {city: 'Kabupaten Halmahera Barat', province_id: 19},
        {city: 'Kabupaten Halmahera Tengah', province_id: 19},
        {city: 'Kabupaten Halmahera Timur', province_id: 19},
        {city: 'Kabupaten Halmahera Selatan', province_id: 19},
        {city: 'Kabupaten Halmahera Utara', province_id: 19},
        {city: 'Kabupaten Kepulauan Sula', province_id: 19},
        {city: 'Kabupaten Pulau Morotai', province_id: 19},
        {city: 'Kabupaten Pulau Taliabu', province_id: 19},
        {city: 'Kota Ternate', province_id: 19},
        {city: 'Kota Tidore Kepulauan', province_id: 19},
        {city: 'Kabupaten Bima', province_id: 20},
        {city: 'Kabupaten Dompu', province_id: 20},
        {city: 'Kabupaten Lombok Barat', province_id: 20},
        {city: 'Kabupaten Lombok Tengah', province_id: 20},
        {city: 'Kabupaten Lombok Timur', province_id: 20},
        {city: 'Kabupaten Lombok Utara', province_id: 20},
        {city: 'Kabupaten Sumbawa', province_id: 20},
        {city: 'Kabupaten Sumbawa Barat', province_id: 20},
        {city: 'Kota Bima', province_id: 20},
        {city: 'Kota Mataram', province_id: 20},
        {city: 'Kabupaten Alor', province_id: 21},
        {city: 'Kabupaten Belu', province_id: 21},
        {city: 'Kabupaten Ende', province_id: 21},
        {city: 'Kabupaten Flores', province_id: 21},
        {city: 'Kabupaten Kupang', province_id: 21},
        {city: 'Kabupaten Lembata', province_id: 21},
        {city: 'Kabupaten Malaka', province_id: 21},
        {city: 'Kabupaten Manggarai', province_id: 21},
        {city: 'Kabupaten Manggarai Barat', province_id: 21},
        {city: 'Kabupaten Manggarai Timur', province_id: 21},
        {city: 'Kabupaten Ngada', province_id: 21},
        {city: 'Kabupaten Nagekeo', province_id: 21},
        {city: 'Kabupaten Rote Ndao', province_id: 21},
        {city: 'Kabupaten Sabu Raijua', province_id: 21},
        {city: 'Kabupaten Sikka', province_id: 21},
        {city: 'Kabupaten Sumba Barat', province_id: 21},
        {city: 'Kabupaten Sumba Barat Daya', province_id: 21},
        {city: 'Kabupaten Sumba Tengah', province_id: 21},
        {city: 'Kabupaten Sumba Timur', province_id: 21},
        {city: 'Kabupaten Timor Tengah Selatan', province_id: 21},
        {city: 'Kabupaten Timor Tengah Utara', province_id: 21},
        {city: 'Kota Kupang', province_id: 21},
        {city: 'Kabupaten Asmat', province_id: 22},
        {city: 'Kabupaten Biak Numpor', province_id: 22},
        {city: 'Kabupaten Boven Digoel', province_id: 22},
        {city: 'Kabupaten Deiyai', province_id: 22},
        {city: 'Kabupaten Dogiayi', province_id: 22},
        {city: 'Kabupaten Intan Jaya', province_id: 22},
        {city: 'Kabupaten Jayapura', province_id: 22},
        {city: 'Kabupaten Jayawijaya', province_id: 22},
        {city: 'Kabupaten Keerom', province_id: 22},
        {city: 'Kabupaten Kepulauan Yapen', province_id: 22},
        {city: 'Kabupaten Lanny Jaya', province_id: 22},
        {city: 'Kabupaten Mamberamo Tengah', province_id: 22},
        {city: 'Kabupaten Mappi', province_id: 22},
        {city: 'Kabupaten Merauke', province_id: 22},
        {city: 'Kabupaten Mimika', province_id: 22},
        {city: 'Kabupaten Nabire', province_id: 22},
        {city: 'Kabupaten Nduga', province_id: 22},
        {city: 'Kabupaten Paniai', province_id: 22},
        {city: 'Kabupaten Pegunungan Bintang', province_id: 22},
        {city: 'Kabupaten Puncak', province_id: 22},
        {city: 'Kabupaten Puncak Jaya', province_id: 22},
        {city: 'Kabupaten Sarmi', province_id: 22},
        {city: 'Kabupaten Supiori', province_id: 22},
        {city: 'Kabupaten Tolikara', province_id: 22},
        {city: 'Kabupaten Waropen', province_id: 22},
        {city: 'Kabupaten Yahukimo', province_id: 22},
        {city: 'Kabupaten Yalimo', province_id: 22},
        {city: 'Kota Jayapura', province_id: 22},
        {city: 'Kabupaten Fakfak', province_id: 23},
        {city: 'Kabupaten Kainama', province_id: 23},
        {city: 'Kabupaten Monokwari', province_id: 23},
        {city: 'Kabupaten Maybrat', province_id: 23},
        {city: 'Kabupaten Pegunungan Arfak', province_id: 23},
        {city: 'Kabupaten Raja Ampat', province_id: 23},
        {city: 'Kabupaten Sorong', province_id: 23},
        {city: 'Kabupaten Sorong Selatan', province_id: 23},
        {city: 'Kabupaten Tambarauw', province_id: 23},
        {city: 'Kabupaten Teluk Bintuni', province_id: 23},
        {city: 'Kabupaten Teluk Wondama', province_id: 23},
        {city: 'Kota Sorong', province_id: 23},
        {city: 'Kabupaten Bengkalis', province_id: 24},
        {city: 'Kabupaten Indragiri Hilir', province_id: 24},
        {city: 'Kabupaten Indragiri Hulu', province_id: 24},
        {city: 'Kabupaten Kampar', province_id: 24},
        {city: 'Kabupaten Kepulauan Meranti', province_id: 24},
        {city: 'Kabupaten Kuantan Singingi', province_id: 24},
        {city: 'Kabupaten Pelalawan', province_id: 24},
        {city: 'Kabupaten Rokan Hilir', province_id: 24},
        {city: 'Kabupaten Rokan Hulu', province_id: 24},
        {city: 'Kabupaten Siak', province_id: 24},
        {city: 'Kota Dumai', province_id: 24},
        {city: 'Kota Pekanbaru', province_id: 24},
        {city: 'Kabupaten Majane', province_id: 25},
        {city: 'Kabupaten Mamasa', province_id: 25},
        {city: 'Kabupaten Mamuju', province_id: 25},
        {city: 'Kabupaten Mamuju Tengah', province_id: 25},
        {city: 'Kabupaten Pasangkayu', province_id: 25},
        {city: 'Kabupaten Polewali Mandar', province_id: 25},
        {city: 'Kabupaten Bantaeng', province_id: 26},
        {city: 'Kabupaten Barru', province_id: 26},
        {city: 'Kabupaten Bone', province_id: 26},
        {city: 'Kabupaten Bulukumba', province_id: 26},
        {city: 'Kabupaten Enrekang', province_id: 26},
        {city: 'Kabupaten Gowa', province_id: 26},
        {city: 'Kabupaten Jeneponto', province_id: 26},
        {city: 'Kabupaten Kepulauan Selayar', province_id: 26},
        {city: 'Kabupaten Luwu', province_id: 26},
        {city: 'Kabupaten Luwu Timur', province_id: 26},
        {city: 'Kabupaten Luwu Utara', province_id: 26},
        {city: 'Kabupaten Maros', province_id: 26},
        {city: 'Kabupaten Pangkajene dan Kepulauan', province_id: 26},
        {city: 'Kabupaten Pinrang', province_id: 26},
        {city: 'Kabupaten Sindenreng Rappang', province_id: 26},
        {city: 'Kabupaten Sinjai', province_id: 26},
        {city: 'Kabupaten Sopeng', province_id: 26},
        {city: 'Kabupaten Takalar', province_id: 26},
        {city: 'Kabupaten Tana Toraja', province_id: 26},
        {city: 'Kabupaten Toraja Utara', province_id: 26},
        {city: 'Kabupaten Wajo', province_id: 26},
        {city: 'Kota Makassar', province_id: 26},
        {city: 'Kota Palopo', province_id: 26},
        {city: 'Kota Parepare', province_id: 26},
        {city: 'Kabupaten Banggai', province_id: 27,
        {city: 'Kabupaten Banggai Kepulauan', province_id: 27},
        {city: 'Kabupaten Banggai Laut', province_id: 27},
        {city: 'Kabupaten Buol', province_id: 27},
        {city: 'Kabupaten Donggala', province_id: 27},
        {city: 'Kabupaten Morowali', province_id: 27},
        {city: 'Kabupaten Morowali Utara', province_id: 27},
        {city: 'Kabupaten Parigi Moutong', province_id: 27},
        {city: 'Kabupaten Poso', province_id: 27},
        {city: 'Kabupaten Sigi', province_id: 27},
        {city: 'Kabupaten Tojo Una-Una', province_id: 27},
        {city: 'Kabupaten Tolitoli', province_id: 27},
        {city: 'Kota Palu', province_id: 27},
        {city: 'Kabupaten Bombana', province_id: 28},
        {city: 'Kabupaten Buton', province_id: 28},
        {city: 'Kabupaten Buton Selatan', province_id: 28},
        {city: 'Kabupaten Buton Tengah', province_id: 28},
        {city: 'Kabupaten Buton Utara', province_id: 28},
        {city: 'Kabupaten Kolaka', province_id: 28},
        {city: 'Kabupaten Kolaka Timur', province_id: 28},
        {city: 'Kabupaten Kolaka Utara', province_id: 28},
        {city: 'Kabupaten Konawe', province_id: 28},
        {city: 'Kabupaten Konawe Kepulauan', province_id: 28},
        {city: 'Kabupaten Konawe Selatan', province_id: 28},
        {city: 'Kabupaten Konawe Utara', province_id: 28},
        {city: 'Kabupaten Muna', province_id: 28},
        {city: 'Kabupaten Muna Barat', province_id: 28},
        {city: 'Kabupaten Wakatobi', province_id: 28},
        {city: 'Kota Bau-Bau', province_id: 28},
        {city: 'Kota Kendari', province_id: 28},
        {city: 'Kabupaten Bolaang Mongondow', province_id: 29},
        {city: 'Kabupaten Bolaang Mongondow Selatan', province_id: 29},
        {city: 'Kabupaten Bolaang Mongondow Timur', province_id: 29},
        {city: 'Kabupaten Bolaang Mongondow Utara', province_id: 29},
        {city: 'Kabupaten Kepulauan Sangihe', province_id: 29},
        {city: 'Kabupaten Kepulauan Siau Tagulandang Biaro', province_id: 29},
        {city: 'Kabupaten Kepulauan Talaud', province_id: 29},
        {city: 'Kabupaten Minahasa', province_id: 29},
        {city: 'Kabupaten Minahasa Selatan', province_id: 29},
        {city: 'Kabupaten Minahasa Tenggara', province_id: 29},
        {city: 'Kabupaten Minahasa Utara', province_id: 29},
        {city: 'Kota Bitung', province_id: 29},
        {city: 'Kota Kotaobagu', province_id: 29},
        {city: 'Kota Manado', province_id: 29},
        {city: 'Kota Tomohon', province_id: 29},
        {city: 'Kabupaten Agam', province_id: 30},
        {city: 'Kabupaten Dharmasraya', province_id: 30},
        {city: 'Kabupaten Kepulauan Mentawai', province_id: 30},
        {city: 'Kabupaten Lima Puluh Kota', province_id: 30},
        {city: 'Kabupaten Padang Pariaman', province_id: 30},
        {city: 'Kabupaten Pasaman', province_id: 30},
        {city: 'Kabupaten Pasaman Barat', province_id: 30},
        {city: 'Kabupaten Pesisir Selatan', province_id: 30},
        {city: 'Kabupaten Sijunjung', province_id: 30},
        {city: 'Kabupaten Solok', province_id: 30},
        {city: 'Kabupaten Solok Selatan', province_id: 30},
        {city: 'Kabupaten Tanah Datar', province_id: 30},
        {city: 'Kota Bukittinggi', province_id: 30},
        {city: 'Kota Padang', province_id: 30},
        {city: 'Kota Padang Panjang', province_id: 30},
        {city: 'Kota Pariaman', province_id: 30},
        {city: 'Kota Payakumbuh', province_id: 30},
        {city: 'Kota Sawahlunto', province_id: 30},
        {city: 'Kota Solok', province_id: 30},
        {city: 'Kabupaten Banyuasin', province_id: 31},
        {city: 'Kabupaten Empat Lawang', province_id: 31},
        {city: 'Kabupaten Lahat', province_id: 31},
        {city: 'Kabupaten Muara Enim', province_id: 31},
        {city: 'Kabupaten Musi Banyuasin', province_id: 31},
        {city: 'Kabupaten Musi Rawas', province_id: 31},
        {city: 'Kabupaten Musi Rawas Utara', province_id: 31},
        {city: 'Kabupaten Ogan Llir', province_id: 31},
        {city: 'Kabupaten Ogan Komering Llir', province_id: 31},
        {city: 'Kabupaten Ogan Komering Ulu Selatan', province_id: 31},
        {city: 'Kabupaten Ogan Komering Ulu Timur', province_id: 31},
        {city: 'Kabupaten Penukal Abab Lematang Llir', province_id: 31},
        {city: 'Kota Lubuklinggau', province_id: 31},
        {city: 'Kota Pagar Alam', province_id: 31},
        {city: 'Kota Palembang', province_id: 31},
        {city: 'Kota Prabumulih', province_id: 31},
        {city: 'Kabupaten Asahan', province_id: 32},
        {city: 'Kabupaten Batubara', province_id: 32},
        {city: 'Kabupaten Dairi', province_id: 32},
        {city: 'Kabupaten Deli Serdang', province_id: 32},
        {city: 'Kabupaten Humbang Hasundutan', province_id: 32},
        {city: 'Kabupaten Karo', province_id: 32},
        {city: 'Kabupaten Labuhanbatu', province_id: 32},
        {city: 'Kabupaten Labuhanbatu Selatan', province_id: 32},
        {city: 'Kabupaten Labuhanbatu Utara', province_id: 32},
        {city: 'Kabupaten Langkat', province_id: 32},
        {city: 'Kabupaten Mandaling Natal', province_id: 32},
        {city: 'Kabupaten Nias', province_id: 32},
        {city: 'Kabupaten Nias Barat', province_id: 32},
        {city: 'Kabupaten Nias Selatan', province_id: 32},
        {city: 'Kabupaten Nias Utara', province_id: 32},
        {city: 'Kabupaten Padang Lawas', province_id: 32},
        {city: 'Kabupaten Padang Lawas Utara', province_id: 32},
        {city: 'Kabupaten Pakpak Bharat', province_id: 32},
        {city: 'Kabupaten Samosir', province_id: 32},
        {city: 'Kabupaten Serdang Bedagai', province_id: 32},
        {city: 'Kabupaten Simalungun', province_id: 32},
        {city: 'Kabupaten Tapanuli Selatan', province_id: 32},
        {city: 'Kabupaten Tapanuli Tengah', province_id: 32},
        {city: 'Kabupaten Tapanuli Utara', province_id: 32},
        {city: 'Kabupaten Toba Samosir', province_id: 32},
        {city: 'Kota Binjai', province_id: 32},
        {city: 'Kota Gunungsitoli', province_id: 32},
        {city: 'Kota Medan', province_id: 32},
        {city: 'Kota Padangsidempuan', province_id: 32},
        {city: 'Kota Pematangsiantar', province_id: 32},
        {city: 'Kota Sibolga', province_id: 32},
        {city: 'Kota Tanjungbalai', province_id: 32},
        {city: 'Kota Tebing Tinggi', province_id: 32},
        {city: 'Kabupaten Bantul', province_id: 33},
        {city: 'Kabupaten Gunungkidul', province_id: 33},
        {city: 'Kabupaten Kulon Progo', province_id: 33},
        {city: 'Kabupaten Sleman', province_id: 33},
        {city: 'Kota Yogyakarta', province_id: 33}
      ]);
    });
};
